import { defineConfig, devices } from '@playwright/test'

const externalBaseURL = process.env.E2E_BASE_URL
const localStagingTLS =
  externalBaseURL !== undefined &&
  new URL(externalBaseURL).protocol === 'https:' &&
  ['localhost', '127.0.0.1', '::1'].includes(new URL(externalBaseURL).hostname)

export default defineConfig({
  testDir: './e2e',
  timeout: 30_000,
  expect: { timeout: 10_000 },
  fullyParallel: false,
  workers: 1,
  forbidOnly: true,
  retries: 0,
  reporter: 'list',
  use: {
    baseURL: externalBaseURL ?? 'http://127.0.0.1:4173',
    // Trust only the ephemeral certificate generated by local staging. This
    // never disables certificate verification for a remote test target.
    ignoreHTTPSErrors: localStagingTLS,
    trace: 'retain-on-failure',
    screenshot: 'only-on-failure',
  },
  webServer: externalBaseURL
    ? undefined
    : {
        command:
          'npm run build && npm run preview -- --host 127.0.0.1 --port 4173',
        env: {
          VITE_DEV_API_PROXY_TARGET:
            process.env.E2E_API_URL ?? 'http://127.0.0.1:8080',
        },
        reuseExistingServer: true,
        timeout: 120_000,
        url: 'http://127.0.0.1:4173',
      },
  projects: [
    { name: 'desktop-chrome', use: { ...devices['Desktop Chrome'] } },
    {
      name: 'mobile-chrome',
      use: { ...devices['Pixel 5'] },
    },
  ],
})
