-- MailerLite affiliate activation.
--
-- The tracking URL below was copied from Andon Pediev's approved MailerLite
-- affiliate dashboard on 2026-08-26. It must not be reconstructed, shortened,
-- or have its ownership parameters changed. MailerLite's current programme is
-- operated through Trackdesk and pays 30% on the initial paid subscription and
-- recurring payments, subject to the programme terms.
--
-- The catalog price is the Comfort monthly price at up to 1,000 subscribers,
-- verified from MailerLite's own pricing material on 2026-08-26. The affiliate
-- link currently lands on the MailerLite home page because that is the exact
-- default link supplied by the programme. Replace destination_url only with a
-- pricing-page link generated by the same approved dashboard.

BEGIN;

INSERT INTO commerce.merchants (
    name, slug, website_url, country_code, trust_score, status
) VALUES (
    'MailerLite', 'mailerlite', 'https://www.mailerlite.com', 'US', 80, 'active'
)
ON CONFLICT (slug) DO UPDATE SET
    name = EXCLUDED.name,
    website_url = EXCLUDED.website_url,
    country_code = EXCLUDED.country_code,
    status = EXCLUDED.status,
    updated_at = now();

INSERT INTO commerce.merchant_offers (
    merchant_id, product_id, merchant_sku, product_url, price_minor,
    shipping_minor, currency, availability, condition, last_checked_at,
    is_active
)
SELECT merchants.id, products.id, 'mailerlite-comfort',
       'https://www.mailerlite.com/pricing', 1900, 0, 'USD', 'in_stock',
       'new', now(), true
FROM commerce.merchants merchants
JOIN catalog.products products ON products.slug = 'mailerlite-comfort'
WHERE merchants.slug = 'mailerlite'
ON CONFLICT (merchant_id, merchant_sku) DO UPDATE SET
    product_id = EXCLUDED.product_id,
    product_url = EXCLUDED.product_url,
    price_minor = EXCLUDED.price_minor,
    shipping_minor = EXCLUDED.shipping_minor,
    currency = EXCLUDED.currency,
    availability = EXCLUDED.availability,
    condition = EXCLUDED.condition,
    last_checked_at = EXCLUDED.last_checked_at,
    is_active = EXCLUDED.is_active,
    updated_at = now();

INSERT INTO commerce.affiliate_links (
    merchant_offer_id, provider, destination_url, external_reference,
    disclosure_label, is_active, priority, program_id, commission_type,
    commission_rate_bps, commission_amount_minor, commission_currency
)
SELECT offers.id, 'trackdesk',
       'https://www.mailerlite.com/?linkId=lp_170762&sourceId=unsolero&tenantId=mailerlite',
       'lp_170762', 'Affiliate link', true, 0, 'mailerlite', 'percentage',
       3000, NULL, NULL
FROM commerce.merchant_offers offers
JOIN commerce.merchants merchants ON merchants.id = offers.merchant_id
WHERE merchants.slug = 'mailerlite'
  AND offers.merchant_sku = 'mailerlite-comfort'
ON CONFLICT (merchant_offer_id, provider) DO UPDATE SET
    destination_url = EXCLUDED.destination_url,
    external_reference = EXCLUDED.external_reference,
    disclosure_label = EXCLUDED.disclosure_label,
    is_active = EXCLUDED.is_active,
    priority = EXCLUDED.priority,
    program_id = EXCLUDED.program_id,
    commission_type = EXCLUDED.commission_type,
    commission_rate_bps = EXCLUDED.commission_rate_bps,
    commission_amount_minor = EXCLUDED.commission_amount_minor,
    commission_currency = EXCLUDED.commission_currency,
    updated_at = now();

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM commerce.affiliate_links links
        JOIN commerce.merchant_offers offers
          ON offers.id = links.merchant_offer_id
        JOIN commerce.merchants merchants
          ON merchants.id = offers.merchant_id
        JOIN catalog.products products
          ON products.id = offers.product_id
        WHERE merchants.slug = 'mailerlite'
          AND products.slug = 'mailerlite-comfort'
          AND offers.merchant_sku = 'mailerlite-comfort'
          AND links.provider = 'trackdesk'
          AND links.destination_url =
              'https://www.mailerlite.com/?linkId=lp_170762&sourceId=unsolero&tenantId=mailerlite'
          AND offers.is_active
          AND links.is_active
    ) THEN
        RAISE EXCEPTION
            'MailerLite affiliate activation failed: required catalog product or commerce row is missing';
    END IF;
END
$$;

COMMIT;
